name: AutoWorldTools
version: 1.5
main: com.github.rypengu23.autoworldtools.AutoWorldTools
api-version: 1.16
authors: [ rypengu23 ]
description: World auto reset plugin
softdepend: ['Multiverse-Core', 'Multiverse-Portals', 'DiscordSRV', 'dynmap']

commands:
  autoworldtools:
    description: メインコマンド
  awt:
    description: 省略版

permissions:
  autoWorldTools.*:
    description: 全ての権限にアクセス可能
    children:
      autoWorldTools.admin: true
  autoWorldTools.admin:
    description: 手動リセット・バックアップ・Configのリロード可能
    default: op
    children:
      autoWorldTools.reset: true
      autoWorldTools.backup: true
      autoWorldTools.resetInfo: true
      autoWorldTools.backupInfo: true
      autoWorldTools.restartInfo: true
  autoWorldTools.reset:
    description: 手動でConfigに登録されたワールドのリセット可能
    default: op
  autoWorldTools.backup:
    description: 手動でワールドのバックアップ可能
    default: op
  autoWorldTools.resetInfo:
    description: リセット時刻情報閲覧可
    default: true
  autoWorldTools.backupInfo:
    description: バックアップ時刻情報閲覧可
    default: true
  autoWorldTools.restartInfo:
    description: 再起動時刻情報閲覧可
    default: true
